### PR TITLE
Add github action for CI

### PR DESCRIPTION
**Pull request by matt335672**
Draft PR - bare-bones CI action to run shellcheck.

Shellcheck is currently failing. When we've merged #2, I'll fix this up and get it working.

### CODE REVIEW

**Comment by akarl10** [comment]
Looking at shellcheck you are right that "$evn" should be quoted everywhere

```bash
echo '#!/bin/sh
test -z "$XDG_RUNTIME_DIR" && exit 1
test -z "$1" && exit 1

SESSION_RUNTIME_DIR="$XDG_RUNTIME_DIR/$1"
install -dm 0700 "$SESSION_RUNTIME_DIR"
oIFS="$IFS"
IFS="
"

# keep only absolutly needed environment variables
for ev in $( env ); do
    evn=${ev%%=*}
    [ "$evn" != "HOME" ] && \
    [ "$evn" != "SHELL" ]  && \
    [ "$evn" != "LANG" ]  && \
    [ "$evn" != "PATH" ]  && \
    [ "$evn" != "SYSTEMD_EXEC_PID" ]  && \
    [ "$evn" != "INVOCATION_ID" ]  && \
    [ "$evn" != "NOTIFY_SOCKET" ]  && \
    [ "$evn" != "MANAGERPID" ] && \
      unset "$evn";
done

IFS="$oIFS"

XDG_RUNTIME_DIR="$SESSION_RUNTIME_DIR"

export XDG_RUNTIME_DIR

exec /lib/systemd/systemd --user
' > $XDG_RUNTIME_DIR/systemd_user_session.sh
```
this "embedded" version does not throw a warning

maybe adding something like
```bash
env XDG_RUNTIME_DIR=. sh ./systemd_user_context.sh prepare
shellcheck systemd_user_session.sh
```
could be used to check this script too

a better solution would obviosly be having this files externally and have a build create the single script and/or a .deb/.rpm /make install that puts the two unit files and systemd_user_session.sh "system-wide" (essentially obsoleting prepare).

**Comment by matt335672** [comment]
Feel free to add more comments. I'll action the ones you've specified above anyway.

**Comment by akarl10** [comment]
LGTM

**Comment by matt335672** [comment]
I've changed the environment variable test logic to use a case rather than `if [] && .. && []`. There are less characters involved.

**Pull request merged**
